# Generated by Django 3.0.7 on 2021-03-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210303_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url_name',
        ),
    ]
