# Generated by Django 3.0.7 on 2021-02-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='n/a', max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
