# Generated by Django 3.0.7 on 2021-02-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(blank=True, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
