# Generated by Django 3.0.7 on 2021-03-03 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20210301_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='author',
            new_name='user_profile',
        ),
    ]
